#!/usr/bin/env python3
"""
basecall_blow5.py
=================
Basecall a BLOW5/SLOW5 file by submitting reads directly to a running
Dorado basecall server via ont-pybasecall-client-lib.

This approach avoids the missing-metadata crash in slow5-dorado standalone,
which expects fields (protocol_run_id, sample_id, protocol_start_time) that
seq2squiggle-generated BLOW5 files do not populate. The basecall server is
tolerant of this because it is designed for live sequencing where incomplete
run metadata is normal.

Requirements
------------
    pip install pyslow5
    pip install ont-pybasecall-client-lib==<server_version>

The ont-pybasecall-client-lib version must exactly match your Dorado
basecall server version. Check with:
    dorado_basecall_server --version

Usage
-----
    python3 basecall_blow5.py \\
        --blow5   community1.blow5 \\
        --fastq   community1_basecalled.fastq \\
        --config  dna_r10.4.1_e8.2_400bps_fast@v5.2.0|| \\
        --address ipc:///var/lib/minknow/data/.dorado/dorado-basecall-server.sock \\
        [--batch-size 4096] \\
        [--timeout  60] \\
        [--log-file basecall.log]
"""

import argparse
import logging
import sys
import time

import pyslow5
from pybasecall_client_lib.helper_functions import package_read
from pybasecall_client_lib.pyclient import PyBasecallClient


# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--blow5",   required=True,
                   help="Input BLOW5/SLOW5 file")
    p.add_argument("--fastq",   required=True,
                   help="Output FASTQ file")
    p.add_argument("--config",  required=True,
                   help="Dorado basecall model config string "
                        "(e.g. dna_r10.4.1_e8.2_400bps_fast@v5.2.0||)")
    p.add_argument("--address", required=True,
                   help="Dorado basecall server address "
                        "(e.g. ipc:///var/lib/minknow/data/.dorado/dorado-basecall-server.sock "
                        "or 127.0.0.1:5555)")
    p.add_argument("--batch-size", type=int, default=4096,
                   help="Number of reads per submission batch (default: 4096)")
    p.add_argument("--timeout",    type=int, default=60,
                   help="Per-read timeout in seconds when collecting results "
                        "(default: 60). Total batch timeout = timeout × batch_size.")
    p.add_argument("--log-file", default=None,
                   help="Path to write log messages (default: stderr only)")
    return p.parse_args()


# ---------------------------------------------------------------------------
# Basecalling
# ---------------------------------------------------------------------------

def build_read_dict(read: dict, read_tag: int) -> dict:
    """
    Build the kwargs dict for package_read() from a pyslow5 read record.

    package_read() signature (from pybasecall_client_lib.helper_functions):
        read_id       - str
        raw_data      - numpy int16 array
        daq_offset    - float, offset for pA conversion
        daq_scaling   - float, scale for pA conversion (range / digitisation)
        sampling_rate - float, samples per second
        start_time    - int, samples since experiment start

    read_tag is unused by package_read but kept as a parameter for logging.

    start_time is an auxiliary field in BLOW5 — only present when
    seq_reads(aux="all") is used, and may still be absent in BLOW5 files
    generated by seq2squiggle. Falls back to 0 if missing.
    """
    start_time = read.get("start_time")

    return {
        "read_id":       read["read_id"],
        "raw_data":      read["signal"].astype("int16"),
        "daq_offset":    float(read["offset"]),
        "daq_scaling":   float(read["range"]) / float(read["digitisation"]),
        "sampling_rate": float(read["sampling_rate"]),
        "start_time":    int(start_time) if start_time is not None else 0,
    }


def flush_batch(
    client: PyBasecallClient,
    batch: list,
    fq_out,
    timeout_s: int,
    log: logging.Logger,
) -> int:
    """
    Submit all reads in batch, collect results, write FASTQ records.
    Returns the number of reads successfully basecalled.

    Key points from the PyBasecallClient API:
    - pass_reads() takes a list of pre-packaged read dicts (built with
      package_read()) and submits them all at once. Returns True on success.
    - get_completed_reads() returns List[List[dict]] — a list of batches,
      each batch being a list of result dicts.
    - Each result may have sub_tag > 0 when Dorado splits a read into
      fragments; only sub_tag == 0 is the primary result and should be kept.
    """
    if not batch:
        return 0

    # Package all reads using the library helper, then submit in one call.
    # Retry up to 3 times if the server queue is full (mirrors Readfish).
    packaged = [package_read(**r) for r in batch]
    for attempt in range(3):
        if client.pass_reads(packaged):
            break
        time.sleep(0.05)
    else:
        log.warning("Could not send batch of %d reads after 3 attempts", len(batch))
        return 0

    # Collect results; total timeout scales with batch size.
    deadline  = time.monotonic() + timeout_s * len(batch)
    collected = 0
    n_written = 0

    while collected < len(batch):
        if time.monotonic() > deadline:
            log.warning(
                "Timeout: still waiting for %d/%d reads in this batch",
                len(batch) - collected, len(batch),
            )
            break

        # get_completed_reads() returns List[List[dict]] — iterate both levels.
        results = client.get_completed_reads()
        if not results:
            time.sleep(client.throttle)
            continue

        for res_batch in results:
            for res in res_batch:
                # Skip read fragments — only sub_tag == 0 is the primary result.
                if res.get("sub_tag", 0) > 0:
                    collected += 1
                    continue

                meta     = res["metadata"]
                dataset  = res["datasets"]
                read_id  = meta.get("read_id", "unknown")
                sequence = dataset.get("sequence", "")
                qstring  = dataset.get("qstring", "")
                mean_q   = meta.get("mean_qscore", 0.0)

                if sequence:
                    fq_out.write(
                        f"@{read_id} qs:f:{mean_q:.4f}\n"
                        f"{sequence}\n"
                        f"+\n"
                        f"{qstring}\n"
                    )
                    n_written += 1
                else:
                    log.debug("Empty sequence for read %s — skipping", read_id)

                collected += 1

    return n_written


def basecall(args: argparse.Namespace) -> int:
    """
    Main basecalling loop. Returns number of basecalled reads (exit code 0
    if > 0, exit code 1 otherwise).
    """
    # ── Connect ───────────────────────────────────────────────────────────────
    client = PyBasecallClient(address=args.address, config=args.config)
    client.connect()
    # if not client.connect():
    #     logging.error("Could not connect to Dorado server at %s", args.address)
    #     return 0
    # logging.info(
    #     "Connected to Dorado server at %s with config %s",
    #     args.address, args.config,
    # )

    # ── Stream and submit ─────────────────────────────────────────────────────
    s5 = pyslow5.Open(args.blow5, "r")

    n_submitted  = 0
    n_basecalled = 0
    batch        = []

    try:
        with open(args.fastq, "w") as fq_out:
            for read in s5.seq_reads(aux="all"):
                batch.append(build_read_dict(read, n_submitted))
                n_submitted += 1

                if len(batch) >= args.batch_size:
                    n_basecalled += flush_batch(
                        client, batch, fq_out, args.timeout, logging.getLogger()
                    )
                    batch = []
                    print(
                        f"  Submitted {n_submitted}, basecalled {n_basecalled}...",
                        end="\r", flush=True,
                    )

            # Final partial batch
            n_basecalled += flush_batch(
                client, batch, fq_out, args.timeout, logging.getLogger()
            )
    finally:
        s5.close()
        client.disconnect()

    print(f"\n  Submitted {n_submitted} reads, basecalled {n_basecalled}")
    logging.info(
        "Basecalling complete: %d submitted, %d basecalled",
        n_submitted, n_basecalled,
    )
    return n_basecalled


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    args = parse_args()

    # Configure logging — always write to stderr; optionally also to file
    handlers = [logging.StreamHandler(sys.stderr)]
    if args.log_file:
        handlers.append(logging.FileHandler(args.log_file))
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
        handlers=handlers,
    )

    n = basecall(args)
    if n == 0:
        logging.error(
            "No reads were basecalled. "
            "Check that the server is running and the config string is correct."
        )
        sys.exit(1)


if __name__ == "__main__":
    main()